### ISSUE TITLE
Inspect request and response body

### ISSUE THREAD

**Issue by TheBronx** [james-proxy/james#260]
Is it possible to see the request and response body? For requests that contain text/json this is really useful.

Don't know if this is not implemented or I'm just blind haha. I can only see headers, URL, status code method and time.

**Comment by nerdbeere** [comment]
Hi,
the data is there, unfortunately it's not implemented in the UI.

**Comment by tomitm** [comment]
Some thoughts on the UI for this:

1. Put the body at the bottom of what we currently have
  - Might have a rendering performance cost, but that could be mitigated by hiding the body by default and requiring the user to click a button to show the body.
2. Use tabs, similar to Chrome's devtools
  - Could possibly clash with #76, if we decide to use tabs for displaying multiple requests, but that could be mitigated by using a dropdown to display the multiple requests

Also... I imagine we'd want to show the response raw, rather than attempting to render a preview, right?

**Comment by nerdbeere** [comment]
I would use tabs and basically do it exactly like the devtools are doing things.

**Comment by avboy72** [comment]
Bummer, I finally got a working distro in chrome.... only to find out that I cant see the request/response body.

Raw is fine.  If its JSON would be be a "nice to have" to format it.

**Comment by ne0c0de** [comment]
@avboy72 did you able to see the response body? If yes how? :)

**Comment by nerdbeere** [comment]
It should be a simple fix. All the data you need is here: https://github.com/james-proxy/james/blob/master/src/renderer/component/inspect-request/request-details.js#L39-L56

Feel free to open a PR ❤️

**Comment by Marty** [comment]
I would use tabs too for this wonderful feature :)

**Comment by carsonip** [comment]
Bummer. How could such an important function be missing? At least show it in an ugly way. I would love to see this function.

**Comment by mitchhentges** [comment]
> How could such an important function be missing?

I agree that the feature could be really useful, but sometimes maintainers have other priorities to fulfill.
As always, feel free to submit a PR.

**Comment by carsonip** [comment]
@mitchhentges It is my first time using a proxy for debugging. I tried james first but moved to mitmproxy after realizing james couldn't show response body. I'm not a React ninja but I can mess around and make a PR if I have time.

**Comment by nerdbeere** [comment]
This will be fixed by #377
