### ISSUE TITLE
App crashes after receiving some packets

### ISSUE THREAD

**Issue by jamezrin** [james-proxy/james#405]
I repeatedly get this exception which crashes the app when running on production mode.

![image](https://user-images.githubusercontent.com/5949554/50560337-24cbae00-0d00-11e9-8152-5f26f31c4362.png)

In the dev console I get
```
hoxy error:  ECONNREFUSED { Error: connect ECONNREFUSED 0.0.0.0:80
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '0.0.0.0',
    port: 80 }
```

And also 
```
ERROR: Error: connect ECONNREFUSED 0.0.0.0:443
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1161:14)
```

I'm running Linux, I tried installing the AppImage build provided and cloning and running it myself.
It might be useful to know that I run a network wide adblocker, PiHole. Which I thought could interfere with James but disabling it doesn't make James to stop crashing, it didn't seem to help.
I have the certificates correctly generated and I'm proxifying the traffic from an Android device to James.

**Comment by jamezrin** [comment]
I worked around this by adding this handler
```
process.on('uncaughtException', (event) => {
  if (event.code === 'ECONNRESET') {
    console.warn('uncaught connection reset'); // eslint-disable-line
  } else if (event.code === 'ECONNREFUSED') {
    console.warn('uncaught refused connection'); // eslint-disable-line
  }
});
```

**Comment by mitchhentges** [comment]
Hmm, investigating this further, the issue doesn't show up in "development mode" because Electron absorbs the error and logs it.

This explains why it wasn't obvious in local development.
In related news, when I tested the `process.on('uncaughtException')` locally, it worked in development mode. However, once a release was created, the issue re-appeared.

I'm not sure why Electron is stopping upon receiving a "fatal error" if we're intercepting it. Maybe we need to do something Electron-specific rather than `process.on(...)`?

Either way, more investigation is needed

**Comment by kadamgreene** [comment]
Is there a new version of James available with this fix in it??

**Comment by mitchhentges** [comment]
Not yet, this issue was trickier than it first seemed.
I haven't had the time to debug further into this, but PRs are always welcome :)

**Comment by jamezrin** [comment]
I think this is fixed in this [PR](https://github.com/greim/hoxy/pull/110).
How can this be incorporated into james without having to wait for it to get merged?
The project seems a bit inactive in my opinion.
